spring:
  application:
    name: RabbitMQ-Demo
  rabbitmq:
    host: 192.168.42.230
    port: 5672
    username: root
    password: root
    publisher-confirms: true  #开启确认消息是否到达交换器，需要设置为true
    publisher-returns: true   #开启确认消息是否到达队列，需要设置为true
    #spring.rabbitmq.virtual-host: test
    virtual-host: /qq