server:
  servlet:
#    context-path: /th-demo
    context-path: /
  port: 8888


spring:
##thymeleaf 页面跳转
  thymeleaf:
#    enabled: false
    prefix: classpath:/templates/
    suffix: .html
##配置数据源

#  datasource:
#    type: org.h2.jdbcx.JdbcDataSource
#    url: jdbc:h2:tcp://127.0.0.1:8043/mem:testbpmn
#    username: root
#    password:


  redis:
    host: 192.168.42.140
    port: 6379
    password: liwen

    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1


jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间 1个小时
  expiration: 3600000
  #  expiration: 60000
  auth:
    # 授权路径
    path: /login
    # 获取用户信息
    account: /info