server:
  servlet:
#    context-path: /th-demo
    context-path: /
  port: 9001
spring:
#  main:
#    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: 123.com
    url: jdbc:mysql://192.168.42.136:3306/data_flow_test?serverTimezone=Hongkong&useUnicode=true&useSSL=false&characterEncoding=utf8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      max-lifetime: 60000
      data-source-properties:
        maintainTimeStats: false
        prepStmtCacheSqlLimit: 2048
        rewriteBatchedStatements: true
        elideSetAutoCommits: true
        cacheResultSetMetadata: true
        cachePrepStmts: true
        prepStmtCacheSize: 250
        useServerPrepStmts: true
        useLocalSessionState: true
        cacheServerConfiguration: true
      validation-timeout: 3000
      minimum-idle: 10
      idle-timeout: 30000
      maximum-pool-size: 200
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: boot_admin_client





#TXN的mq配置
rocketmq:
  nameserver: 10.0.8.16:9876
  producer:
    access-key: AnytxnMQ
    secret-key: any123456
    group: ANYTXN

#消费者 RocketMQMessageListener
  consumer:
    access-key: AnytxnMQ
    secret-key: any123456
