server:
  servlet:
#    context-path: /th-demo
    context-path: /
  port: 9099

h2Service:
  ##thymeleaf 页面跳转
spring:
##thymeleaf 页面跳转
  thymeleaf:
#    enabled: false
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
##配置数据源
#  datasource:
#      druid:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driverClassName: org.h2.Driver
#        url: jdbc:h2:tcp://127.0.0.1:8043/mem:testbpmn
##        url: jdbc:log4jdbc:mysql://192.168.42.136:3306/eladmin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
#        username: root
#        password:
