
#总观中心权限配置
filter:
  context-path: /
  setting:
    allows:
    - /login
    - /logout
    - /change/project
    - /auth/model
    - /navbar
    - /userInfo
    - /project/all
    - /change/project
    - /auth/model
    - /**/favicon.ico
    - /assets/**
    - /css/**
    - /js/**
    - /swagger-ui.html/**
    - /webjars/**
    - /swagger-resources/**
    - /v2/api-docs/**
    - /api/**
    - /actuator/**
    - /p/assets/**
    - /p/js/**
    - /p/css/**
    - /link/menu
    - /account/detail
    - /dashboard/**
    authAddress: http://172.16.101.42:9600
    indexUrl: http://172.16.101.41:9090/${server.context-path}/p/index.html#/
    localUrl: http://172.16.101.41:9090
    authViewScopeUrl: ${filter.setting.authAddress}/api/user/viewScope
    authResourceUrl: ${filter.setting.authAddress}/api/user/resource
    authUrl: ${filter.setting.authAddress}/api/auth/valid
    authUserUrl: ${filter.setting.authAddress}/api/user/info
    authErrorUrl: ${filter.setting.indexUrl}
    authContentUrl: ${filter.setting.authAddress}/api/user/content2
    authAble: true
    loginErrorUrl: ${filter.setting.indexUrl}/#/login/LoginError
    authLoginUrl: ${filter.setting.authAddress}/mc/page/login.html
    serviceId: SDCUbvhEniceJoEjEM
    changeProject: ${filter.setting.authAddress}/api/user/refresh/project
    projectsUrl: ${filter.setting.authAddress}/api/user/projects
    servicePre: ${filter.context-path}
    noAuthUrl: ${filter.setting.indexUrl}

spring:
  cloud:
    rdbms:
      initialize:
        enable: false
    dataflow:
      features:
        analytics-enabled: false
        streams-enabled: false
    deployer:
      local:
        java-opts: -Xms128M -Xmx128M
        workingDirectoriesRoot: /home/jrxany/batch_schedule/workspace
    config:
      enabled: false
  output:
    ansi:
      enabled: always
  application:
    name: task-schedule-system
 #调度中心数据源配置
  datasource:
    password: mysqlhan
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.101.56:3306/any_schedule_center?serverTimezone=Hongkong&useUnicode=true&useSSL=false&characterEncoding=utf8
    hikari:
      connection-timeout: 60000
      max-lifetime: 60000
      data-source-properties:
        maintainTimeStats: false
        prepStmtCacheSqlLimit: 2048
        rewriteBatchedStatements: true
        elideSetAutoCommits: true
        cacheResultSetMetadata: true
        cachePrepStmts: true
        prepStmtCacheSize: 250
        useServerPrepStmts: true
        useLocalSessionState: true
        cacheServerConfiguration: true
      validation-timeout: 3000
      minimum-idle: 30
      idle-timeout: 30000
      maximum-pool-size: 200
    username: root
  batch:
    initialize-schema: never
    initializer:
      enabled: false
 #spring admin 管理中心配置
  boot:
    admin:
      url: http://172.16.102.24:8889

#调度中心 执行节点配置
jrx:
  batch:
    node:
      server:
        server-addr: 172.16.101.29:8848,172.16.101.30:8848,172.16.101.31:8848
        namespace: 09ef3f23-52e0-4d51-b9aa-3364a47619f1
        #执行节点指定  IP节点配置
      address:
        local_test: http://localhost:9001
        master_node_test: http://172.16.102.23:9002
        master_node: http://172.16.101.41:9001
        #执行节点  注册中心 节点名称配置
      init-servers: ''
server:
  context-path: act-task-schedule
  port: 9090
pagehelper:
  supportMethodsArguments: true
  reasonable: true
  count: countSql
  helperDialect: mysql
management:
  security:
    enabled: false
  context-path: /management
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: jrx.batch.scheduling.model
  #调度定时任务配置
batch:
  scheduling:
    partition-timeout-seconds: 60
    monitor-server: true
    external-execution-url: http://localhost:9090/%s
    monitor-partition: true
    monitor-master: true
    monitor-plan: true

citic:
  sso:
    open: true
