server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.42.136:3306/quartz_test?serverTimezone=Hongkong&useUnicode=true&useSSL=false&characterEncoding=utf8
#    url: jdbc:mysql://192.168.42.136:3306/batch_flow?serverTimezone=Hongkong&useUnicode=true&useSSL=false&characterEncoding=utf8
    #    url: jdbc:mysql://192.168.42.136:3306/data_flow?serverTimezone=Hongkong&useUnicode=true&useSSL=false&characterEncoding=utf8
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
