server:
  servlet:
#    context-path: /th-demo
    context-path: /
  port: 9001
spring:
#  main:
#    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: 123.com
    url: jdbc:mysql://192.168.42.136:3306/data_flow_test?serverTimezone=Hongkong&useUnicode=true&useSSL=false&characterEncoding=utf8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      max-lifetime: 60000
      data-source-properties:
        maintainTimeStats: false
        prepStmtCacheSqlLimit: 2048
        rewriteBatchedStatements: true
        elideSetAutoCommits: true
        cacheResultSetMetadata: true
        cachePrepStmts: true
        prepStmtCacheSize: 250
        useServerPrepStmts: true
        useLocalSessionState: true
        cacheServerConfiguration: true
      validation-timeout: 3000
      minimum-idle: 10
      idle-timeout: 30000
      maximum-pool-size: 200
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: boot_admin_client


  # 生产者的组名
suning:
  rocketmq:
    producer-group: anybatch_pro_group_job_server
  # 消费者的组名
    conumer-group: anybatch_customer_group_exec_node
  # NameServer地址
    namesrvaddr: 10.0.8.16:9876
    accessKey: BatchTaskMQ
    secretKey:  batch123456
    topic: ANY_BATCH_JOB_RESULT_STATUE_TOPIC



#生产者 RocketMQProperties
rocketmq:
  nameserver: 10.0.8.16:9876
  producer:
    access-key: BatchTaskMQ
    secret-key: batch123456
    group: anybatch_pro_group_job_server

#消费者 RocketMQMessageListener
  consumer:
    access-key: BatchTaskMQ
    secret-key: batch123456
#    groupname: anybatch_customer_group_exec_node
