server:
  servlet:
#    context-path: /th-demo
    context-path: /
  port: 11000
spring:
#  main:
#    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.42.136:3306/data_flow_test?serverTimezone=Hongkong&useUnicode=true&useSSL=false&characterEncoding=utf8

    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      max-lifetime: 60000
      data-source-properties:
        maintainTimeStats: false
        prepStmtCacheSqlLimit: 2048
        rewriteBatchedStatements: true
        elideSetAutoCommits: true
        cacheResultSetMetadata: true
        cachePrepStmts: true
        prepStmtCacheSize: 250
        useServerPrepStmts: true
        useLocalSessionState: true
        cacheServerConfiguration: true
      validation-timeout: 3000
      minimum-idle: 10
      idle-timeout: 30000
      maximum-pool-size: 200
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: springboot_redis

# Redis数据库索引（默认为0）
  redis:
    database: 0
  # Redis服务器地址
    host: 192.168.42.140
  # Redis服务器连接端口
    port: 6379
  # Redis服务器连接密码（默认为空）
    password: liwen
  # 连接池最大连接数（使用负值表示没有限制）
#    pool.max-active: 200
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    pool.max-wait: -1
  # 连接池中的最大空闲连接
#    pool.max-idle: 10
  # 连接池中的最小空闲连接
#    pool.min-idle: 0
  # 连接超时时间（毫秒）
    timeout: 1000
