spring:
  profiles:
    active: local
#    active: dev
  application:
    name: node_local_test
  boot:
    admin:
      client:
        url: http://172.16.102.24:8889

management:
  server:
    port: 8079
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
      region: test_boot_admin





