##配置数据源
mybatis.path: com/architect/all/spring/security/config/mybatis/mybatis.yml

#  mapperLocations: ["classpath:com/architect/all/spring/security/**/dao/mapper/*.xml"]

#  dataSource: dataSource

#  #配置 Jpa
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    open-in-view: true
#
#  jackson:
#    time-zone: GMT+8
#
#  redis:
#    #数据库索引
#    database: 0
#    host: 192.168.42.140
#    port: 6379
#    password: liwen
#    jedis:
#      pool:
#        #最大连接数
#        max-active: 100
#        #最大阻塞等待时间(负数表示没限制)
#        max-wait: 2000
#        #最大空闲
#        max-idle: 500
#        #最小空闲
#        min-idle: 8
#    #连接超时时间
#    timeout: 5000
#
##jwt
#jwt:
#  header: Authorization
#  secret: mySecret
#  # token 过期时间 1个小时
#  expiration: 3600000
##  expiration: 60000
#  auth:
#    # 授权路径
#    path: /login
#    # 获取用户信息
#    account: /info